server:
  port: 8004

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:~/polymorphism;MODE=MSSQLServer;IGNORECASE=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: create

  h2:
    console:
      enabled: true
